version: "3"
services:
  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    networks:
      - app-network
  backend:
    build:
      context: ./backend
    container_name: react-nestjs-app
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    networks:
      - app-network
  db:
    image: postgres:13
    container_name: react-postgres-db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
